version: '2.2'

services:
  elasticsearch:
    image: elasticsearch:6.8.22
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - elk


  kibana:
    image: kibana:6.8.22
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  grafana:
    image:  grafana/grafana:8.3.3
    ports:
        - "3000:3000"
    volumes:
        - "./grafana:/var/lib/grafana"
    networks:
      - elk

networks:
  elk:
    driver: bridge